ItemEvents.modifyTooltips(event => {
	event.add("minecraft:ender_eye",Text.gray("The eye looks towards the end..."))
	event.add("starcatcher:clam",Text.gray("I think if it is left alone on the sand it might open up"))
	event.add("vinery:apple_mash",Text.gray("Can be bottled in apple press using wine bottles"))
	event.add("minecraft:bone_meal",Text.gray("Can be used to lure out worms out of framland"))
	event.add("supplementaries:soap",Text.gray("Color'b'Gone!"))
	event.modify(/_knife/, tooltip=>{tooltip.insert(1,Text.gray("Slaughtering animals and cutting grass may provide unique drops"))})
	event.modify(/tackle_box_/, tooltip=>{tooltip.insert(1,Text.gray("Can be used to modify your fishing rod. Also can store LOTS of fish!"))})
	event.add("#c:villager_job_sites",{shift:false},Text.gray("Villager info: [Shift]"))
	event.add("betterarcheology:archeology_table",{shift:false},Text.gray("Villager info: [Shift]"))
	event.add("vinery:fermentation_barrel",{shift:false},Text.gray("Villager info: [Shift]"))
	event.add("#c:villager_job_sites",{shift:true},Text.gray("Serves as valid villager job station"))
	event.add("betterarcheology:archeology_table",{shift:true},Text.gray("Serves as valid villager job station"))
	event.add("betterarcheology:archeology_table",{shift:true},Text.gray("Profession: Archaeologist"))
	event.add("vinery:fermentation_barrel",{shift:true},Text.gray("Serves as valid villager job station"))
	event.add("vinery:fermentation_barrel",{shift:true},Text.gray("Profession: Winemaker"))
	event.add("biomeswevegone:foragers_table",{shift:true},Text.gray("Profession: Forager"))
	event.add("minecraft:barrel",{shift:true},Text.gray("Profession: Fisherman"))
	event.add("minecraft:lectern",{shift:true},Text.gray("Profession: Librarian"))
	event.add("minecraft:cauldron",{shift:true},Text.gray("Profession: Leatherworker"))
	event.add("minecraft:brewing_stand",{shift:true},Text.gray("Profession: Cleric"))
	event.add("minecraft:composter",{shift:true},Text.gray("Profession: Farmer"))
	event.add("minecraft:blast_furnace",{shift:true},Text.gray("Profession: Armorer"))
	event.add("minecraft:smoker",{shift:true},Text.gray("Profession: Butcher"))
	event.add("minecraft:loom",{shift:true},Text.gray("Profession: Shepard"))
	event.add("minecraft:grindstone",{shift:true},Text.gray("Profession: Weaponsmith"))
	event.add("minecraft:smithing_table",{shift:true},Text.gray("Profession: Toolsmith"))
	event.add("minecraft:fletching_table",{shift:true},Text.gray("Profession: Fletcher"))
	event.add("minecraft:cartography_table",{shift:true},Text.gray("Profession: Cartographer"))
	event.add("minecraft:stonecutter",{shift:true},Text.gray("Profession: Mason"))
})
