StartupEvents.registry('item', event => {
// recipes
	event.create('wine_recipe_aegis')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.WHITE : -1)
	.tooltip("\u00A77[\u00A76Aegis Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Taiga White Grape Juice 7%")
	.tooltip("\u00A77 - Sugar")
	.tooltip("\u00A77 - Kelp")
	.tooltip("\u00A77 - Iron Ingot")
	.displayName("Aegis Wine recipe")

	event.create('wine_recipe_apple')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.YELLOW : -1)
	.tooltip("\u00A77[\u00A76Apple Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Apple Juice 15%")
	.tooltip("\u00A77 - Apple Juice")
	.displayName("Apple Wine recipe")

	event.create('wine_recipe_bolvar')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.ORANGE_DYE : -1)
	.tooltip("\u00A77[\u00A76Bolvar Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Taiga Red Grape Juice 6%")
	.tooltip("\u00A77 - Honey Bottle")
	.tooltip("\u00A77 - Cherry")
	.displayName("Bolvar Wine recipe")

	event.create('wine_recipe_chenet')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.GREEN_DYE : -1)
	.tooltip("\u00A77[\u00A76Chenet Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Jungle Red Grape Juice 12%")
	.tooltip("\u00A77 - Honey Bottle")
	.tooltip("\u00A77 - Spider Eye")
	.displayName("Chenet Wine recipe")

	event.create('wine_recipe_cherry')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.RED : -1)
	.tooltip("\u00A77[\u00A76Cherry Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Red Grape Juice 15%")
	.tooltip("\u00A77 - Cherry")
	.displayName("Cherry Wine recipe")

	event.create('wine_recipe_chorus')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.PURPLE_DYE : -1)
	.tooltip("\u00A77[\u00A76Chorus Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Taiga Red Grape Juice 8%")
	.tooltip("\u00A77 - Chorus Fruit")
	.displayName("Chorus Wine recipe")

	event.create('wine_recipe_cider')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.DARK_GREEN : -1)
	.tooltip("\u00A77[\u00A76Cider\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Apple Juice 20%")
	.tooltip("\u00A77 - Sugar")
	.displayName('Cider recipe')

	event.create('wine_recipe_clark')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.LIME_DYE : -1)
	.tooltip("\u00A77[\u00A76Clark Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Jungle White Grape Juice 10%")
	.tooltip("\u00A77 - Sugar")
	.displayName("Clark Wine recipe")

	event.create('wine_recipe_creeper')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.DARK_GRAY : -1)
	.tooltip("\u00A77[\u00A76Creepers Crush\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Savanna White Grape Juice 10%")
	.tooltip("\u00A77 - Gunpowder")
	.displayName('Creepers Crush recipe')

	event.create('wine_recipe_cristel')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.BLUE : -1)
	.tooltip("\u00A77[\u00A76Cristel Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Red Grape Juice 25%")
	.tooltip("\u00A77 - Sugar")
	.tooltip("\u00A77 - Feather")
	.tooltip("\u00A77 - Blaze Rod")
	.displayName("Cristel Wine recipe")

	event.create('wine_recipe_eiswein')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.CYAN_DYE : -1)
	.tooltip("\u00A77[\u00A76Eiswein\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Taiga White Grape Juice 10%")
	.tooltip("\u00A77 - Snowball")
	.displayName("Eiswein recipe")

	event.create('wine_recipe_jellie')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.PINK_DYE : -1)
	.tooltip("\u00A77[\u00A76Jellie Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - White Grape Juice 25%")
	.tooltip("\u00A77 - Apple Wine")
	.tooltip("\u00A77 - Chenet Wine")
	.tooltip("\u00A77 - Bolvar Wine")
	.displayName("Jellie Wine recipe")

	event.create('wine_recipe_jo')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.GOLD : -1)
	.tooltip("\u00A77[\u00A76Jo's Special Mixture\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Savanna Red Grape Juice 10%")
	.tooltip("\u00A77 - Fermented Spider Eye")
	.displayName("Jo's Special Mixture recipe")

	event.create('wine_recipe_kelp')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.DARK_GREEN : -1)
	.tooltip("\u00A77[\u00A76Kelp Cider\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Savanna White Grape Juice 14%")
	.tooltip("\u00A77 - Kelp")
	.displayName("Kelp Cider recipe")

	event.create('wine_recipe_magnet')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.DARK_RED : -1)
	.tooltip("\u00A77[\u00A76Magnetic Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Jungle Red Grape Juice 10%")
	.tooltip("\u00A77 - Iron Ingot")
	.displayName('Magnetic Wine recipe')

	event.create('wine_recipe_mead')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.BROWN_DYE : -1)
	.tooltip("\u00A77[\u00A76Mead\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Apple Juice 1%")
	.tooltip("\u00A77 - Sugar")
	.tooltip("\u00A77 - Honey Bottle")
	.displayName("Mead recipe")

	event.create('wine_recipe_mellohi')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.PINK_DYE : -1)
	.tooltip("\u00A77[\u00A76Mellohi Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - White Grape Juice 5%")
	.tooltip("\u00A77 - Sugar")
	.tooltip("\u00A77 - Glowstone Dust")
	.displayName("Mellohi Wine recipe")

	event.create('wine_recipe_miss')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.DARK_RED : -1)
	.tooltip("\u00A77[\u00A76Miss Lilitus Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Savanna Red Grape Juice 14%")
	.tooltip("\u00A77 - Honey Bottle")
	.tooltip("\u00A77 - Cherry")
	.displayName("Miss Lilitus Wine recipe")

	event.create('wine_recipe_mojang')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.LIME_DYE : -1)
	.tooltip("\u00A77[\u00A76Mojang Noir\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Red Grape Juice 20%")
	.tooltip("\u00A77 - Honney Bottle")
	.tooltip("\u00A77 - Cherry")
	.tooltip("\u00A77 - Red Wine")
	.displayName("Mojang Noir recipe")

	event.create('wine_recipe_noir')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.RED : -1)
	.tooltip("\u00A77[\u00A76Noir Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Red Grape Juice 12%")
	.tooltip("\u00A77 - Sweet Berries")
	.displayName("Noir Wine recipe")

	event.create('wine_recipe_red')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.DARK_RED : -1)
	.tooltip("\u00A77[\u00A76Red Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Red Grape Juice 10%")
	.tooltip("\u00A77 - Sugar")
	.displayName("Red Wine recipe")

	event.create('wine_recipe_solaris')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.GOLD : -1)
	.tooltip("\u00A77[\u00A76Solaris Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - White Grape Juice 15%")
	.tooltip("\u00A77 - Honey Bottle")
	.tooltip("\u00A77 - Sweet Berries")
	.displayName("Solaris Wine recipe")

	event.create('wine_recipe_stal')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.RED : -1)
	.tooltip("\u00A77[\u00A76Stal Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Jungle Red Grape Juice 15%")
	.tooltip("\u00A77 - Sugar")
	.tooltip("\u00A77 - Cocoa Beans")
	.displayName("Stal Wine recipe")

	event.create('wine_recipe_strad')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.BROWN_DYE : -1)
	.tooltip("\u00A77[\u00A76Strad Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Red Grape Juice 8%")
	.tooltip("\u00A77 - Sugar")
	.tooltip("\u00A77 - Cocoa Beans")
	.displayName("Strad Wine recipe")

	event.create('wine_recipe_sun')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.GOLD : -1)
	.tooltip("\u00A77[\u00A76Sun-Kissed Wine\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - White Grape Juice 10%")
	.tooltip("\u00A77 - Glow Berries")
	.displayName("Sun-Kissed Wine recipe")

	event.create('wine_recipe_fright')
	.maxStackSize(1).textures({layer0: 'minecraft:item/map',layer1: 'minecraft:item/filled_map_markings'})
	.color((itemstack, tintIndex) => tintIndex == 1 ? Color.LIGHT_GRAY_DYE : -1)
	.tooltip("\u00A77[\u00A76Villagers Fright\u00A77] \u00A78recipe:")
	.tooltip("\u00A77 - Jungle White Grape Juice 17%")
	.tooltip("\u00A77 - Arrow")
	.displayName("Villagers Fright recipe")
	
// Scrolls
	event.create('wine_recipe_scroll_aegis')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Aegis Wine\u00A77] \u00A78recipe")

	event.create('wine_recipe_scroll_apple')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Apple Wine\u00A77] \u00A78recipe")

	event.create('wine_recipe_scroll_bolvar')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Bolvar Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_chenet')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Chenet Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_cherry')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Cherry Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_chorus')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Chorus Wine\u00A77] \u00A78recipe")

	event.create('wine_recipe_scroll_cider')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Cider\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_clark')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Clark Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_creeper')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Creepers Crush\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_cristel')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Cristel Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_eiswein')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Eiswein\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_jellie')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Jellie Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_jo')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Jo's Special Mixture\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_kelp')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Kelp Cider\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_magnet')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Magnetic Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_mead')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Mead\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_mellohi')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Mellohi Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_miss')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Miss Lilitus Wine\u00A77] \u00A78recipe")

	event.create('wine_recipe_scroll_mojang')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Mojang Noir\u00A77] \u00A78recipe")

	event.create('wine_recipe_scroll_noir')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Noir Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_red')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Red Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_solaris')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Solaris Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_stal')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Stal Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_strad')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Strad Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_sun')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Sun-Kissed Wine\u00A77] \u00A78recipe")
	
	event.create('wine_recipe_scroll_fright')
	.maxStackSize(1).texture("kubejs:item/scroll").use((level, player,hand)=>true).displayName('Wine Recipe Scroll')
	.tooltip("\u00A78Use to discover \u00A77[\u00A76Villagers Fright\u00A77] \u00A78recipe")

})