const IntegerProperty = Java.loadClass("net.minecraft.world.level.block.state.properties.IntegerProperty")

StartupEvents.registry("block", event => {

	const POSE = IntegerProperty.create("pose", 0, 6)


	event.create("dev_plushie_gibbles","kubejs:cardinal")
		.displayName("Dev Plushie: GibbDev")
		.soundType("wool")
		.hardness(1.0)
		.resistance(1.0)
		.tagBlock("kubejs:dev_plushie")
		.tagBlock("minecraft:wool")
		.property(POSE)
		.opaque(false)
		.fullBlock(false)
		.waterlogged()
		.noValidSpawns(true)
		.suffocating(false)
		.transparent(true)
		.noCollision()
		.renderType("cutout")
		.box(4,0,4,12,16,12,true)
		.item(i=>{
			i.rarity("epic")
			.fireResistant(true)
			.maxStackSize(1)
		})
	event.create("dev_plushie_derivoid","kubejs:cardinal")
		.displayName("Dev Plushie: Derivoid")
		.soundType("wool")
		.hardness(1.0)
		.resistance(1.0)
		.tagBlock("kubejs:dev_plushie")
		.tagBlock("minecraft:wool")
		.property(POSE)
		.opaque(false)
		.fullBlock(false)
		.waterlogged()
		.noValidSpawns(true)
		.suffocating(false)
		.transparent(true)
		.noCollision()
		.renderType("cutout")
		.box(4,0,4,12,16,12,true)
		.item(i=>{
			i.rarity("epic")
			.fireResistant(true)
			.maxStackSize(1)
		})
	event.create("dev_plushie_bronwen","kubejs:cardinal")
		.displayName("Dev Plushie: itsbronwen")
		.soundType("wool")
		.hardness(1.0)
		.resistance(1.0)
		.tagBlock("kubejs:dev_plushie")
		.tagBlock("minecraft:wool")
		.property(POSE)
		.opaque(false)
		.fullBlock(false)
		.waterlogged()
		.noValidSpawns(true)
		.suffocating(false)
		.transparent(true)
		.noCollision()
		.renderType("cutout")
		.box(4,0,4,12,16,12,true)
		.item(i=>{
			i.rarity("epic")
			.fireResistant(true)
			.maxStackSize(1)
		})
})