#Determines if mod is enabled
#If "OFF" reverts the recipe book to vanilla behavior
mod_enabled = true
#Determines prefix for search string to let recipe book know you are looking for recipes that use that item
#Default: "$"
ingredient_prefix = "$"
#Determines prefix for search string to let recipe book know you are looking for recipes that are added by certain mod
#Default: "@"
modid_prefix = "@"
#Determines which recipe book UI to use. If "ON" then new custom ui is used. Otherwise modified vanilla one will be rendered
use_custom_ui = true
#If "ON" then there will be help element on recipe book screen that will display controls and prefixes in a tooltip
display_help_button = true
